language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - SSM_USER=$(whoami)
    - DJANGO_STATIC_DIR=/var/local/www/$SSM_USER/static/
    - VENV_HOME=$HOME
    - VENV_DIR=$VENV_HOME/$SSM_USER
services:
  - memcached
before_install:
  - sudo apt-get update
  - sudo apt-get -y install rabbitmq-server
  - sudo service rabbitmq-server start
  - sudo pip install virtualenv
  - echo -e '#!/usr/bin/env bash\n' | sudo tee /usr/sbin/sendmail
  - sudo chmod 755 /usr/sbin/sendmail
install:
  - sudo mkdir -p "$DJANGO_STATIC_DIR"
  - sudo chown $SSM_USER:$SSM_USER "$DJANGO_STATIC_DIR"
  - (cd "$VENV_HOME" && virtualenv "$SSM_USER")
  - bash runinenv.sh "$VENV_DIR" bash setup.sh
script:
  - bash runinenv.sh "$VENV_DIR" bash start-testserver.sh
  - bash runinenv.sh "$VENV_DIR" pip install coverage
  - cd shadowsocks_manager
  - bash ../runinenv.sh "$VENV_DIR" coverage run manage.py test --noinput -v 2
  - bash ../runinenv.sh "$VENV_DIR" coverage xml -o coverage-$TRAVIS_PYTHON_VERSION.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
