language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - SSM_USER=$(whoami)
    - DJANGO_STATIC_DIR=/var/local/www/$SSM_USER/static/
services:
  - memcached
before_install:
  - sudo apt-get update
  - sudo apt-get -y install rabbitmq-server
  - sudo service rabbitmq-server start
install:
  - sudo mkdir -p "$DJANGO_STATIC_DIR"
  - sudo chown $SSM_USER:$SSM_USER "$DJANGO_STATIC_DIR"
  - bash setup.sh
script:
  - bash start-testserver.sh
  - pip install coverage
  - (cd shadowsocks_manager; coverage run --branch --source '.' manage.py test --noinput -v 2)
  - (cd shadowsocks_manager; coverage xml --skip-empty -o coverage-$TRAVIS_PYTHON_VERSION.xml)
after_success:
  - bash <(curl -s https://codecov.io/bash)
