language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - SSM_USER=$(whoami)
    - DJANGO_STATIC_DIR=/var/local/www/$SSM_USER/static/
services:
  - memcached
before_install:
  - sudo apt-get update
  - sudo apt-get -y install rabbitmq-server
  - sudo service rabbitmq-server start
install:
  - sudo mkdir -p "$DJANGO_STATIC_DIR"
  - sudo chown $SSM_USER:$SSM_USER "$DJANGO_STATIC_DIR"
  - bash setup.sh
script:
  - pip install coverage
  - bash start-testserver.sh
  # - python shadowsocks_manager/manage.py test
  - coverage run --source='.' shadowsocks_manager/manage.py test
  - coverage xml --omit='*/migrations/*'
after_success:
  - bash <(curl -s https://codecov.io/bash)
