name: ci-docker

# This workflow builds and pushes a Docker image to DockerHub,
# and tags the commit with the current version of the package.
#
# This workflow is triggered by:
#   - a manual trigger
#   - a release is published

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: |
          version=$(awk -F\" '/^version = / {print $2}' pyproject.toml)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            - ${{ env.DOCKERHUB_USERNAME }}/shadowsocks-manager:latest
            - ${{ env.DOCKERHUB_USERNAME }}/shadowsocks-manager:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
      - name: Set up git user
        run: |
          git config --global user.name "ci-docker.github-actions[bot]"
          git config --global user.email "ci-docker.github.actions[bot]@noreply.github.com"
      - name: Tag commit
        run: git tag -a -m "" "docker-${{ env.VERSION }}"
      - name: Push tag
        run: git push origin "refs/tags/docker-${{ env.VERSION }}"
  
  docker-run:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Docker container
        run: |
          bash install.sh
