name: ci-unittest
on:
  push:
    branches:
      - '**/*'
    paths:
      - '.github/workflows/ci-unittest.yml'
      - 'bin/**'
      - 'setup.cfg'
      - 'setup.py'
      - 'shadowsocks_manager/**'
      - '!shadowsocks_manager/uwsgi.ini'
  pull_request: null
  schedule:
    - cron: 23 11 * * 5
jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7.17', '3.8.18', '3.9.19', '3.10.14', '3.11.9', '3.12.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system packages
        run: |
          pip install --upgrade pip
          echo -e '#!/usr/bin/env bash\n' | sudo tee /usr/sbin/sendmail
          sudo chmod 755 /usr/sbin/sendmail
          docker run -d -p 11211:11211 --name ssm-memcached memcached
          docker run -d -p 5672:5672 --name ssm-rabbitmq rabbitmq
      - name: Install this project
        run: |
          pip install -e .
          ssm-setup -m
      - name: Run Django testcases
        run: |
          pip install coverage
          ssm-test -c
      - name: Upload coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pip install codecov-cli
          ssm-test -u
