name: docker-image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'docker-image'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          echo "::set-output name=VERSION::$(grep -oP 'version = \K.*' setup.cfg)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: alexzhangs/shadowsocks-manager:${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64